version: "3.9"
services:
  database:
    image: mysql/mysql-server:5.6
    container_name: spring-rent-api
    expose:
      - "3307"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "rent"